/**
 * Bundled demo leads for Quote Builder gold scenarios.
 * Used when Sheets mode is Demo and LeadDataFetch returns empty.
 */
export const DEMO_LEAD_ROWS: Record<string, unknown>[] = [
  {
    id: 18900,
    referenceNumber: 'WE.18900',
    name: 'José Rubio / Hannah Charles',
    companyName: 'Space Made Group Limited (T/A Spacemade)',
    companySector: 'Hospitality',
    email: 'jose@spacemade.co / hcc@spacemade.co',
    phone: '07859 003 009',
    jobRole: 'Head of People',
    budget: '£10,000 - £14,999',
    repeatClient: 'No',
    preparedBy: 'Natasha',
    status: 'Good Potential',
    liveDead: 'LIVE',
    source: 'Build your event form',
    enquiryDate: '16-07-2026',
    eventType: 'Christmas Event',
    fullEventDate: 'Wednesday 2nd December 2026',
    eventDateFlexible: 'YES',
    requestedEventTimes: '18:00 - 22:00',
    groupSize: '50 - 65',
    vessels: 'WEOTT II (Avontuur)',
    market: 'Corporate',
    yearOfEvent: 2026,
    assignedRep: 'Natasha',
    groupSizeQuote: 50,
    eventDateFlexibleBool: true,
    eventDateDisplay: 'Date TBC',
    progressNotes:
      'DEMO gold scenario WE.18900 Christmas V4 — Avontuur. Match cost lines from Quote Sheet notes before Generate.',
    quoteWeottCost: 12278.64,
    quoteMarginPercent: 25,
    quoteWeeklyPeriod: 'Mon to Thur',
    quoteDayPeriod: 'Evening',
    quoteGroupBracket: 'Standard',
  },
  {
    id: 18759,
    referenceNumber: 'WE.18759',
    name: 'Mankaasha Umba',
    companyName: 'The Outnet',
    companySector: 'Retail & Consumer Goods',
    email: 'mankaasha.umba.external@theoutnet.com',
    phone: '07944 612 096',
    jobRole: 'Team Assistant',
    budget: 'TBC',
    repeatClient: 'No',
    preparedBy: 'Katherine',
    status: 'Booked',
    liveDead: 'BOOKED',
    source: 'TagVenue',
    enquiryDate: '11-06-2026',
    eventType: 'Summer Event',
    fullEventDate: 'Thursday 23rd July 2026',
    eventDateFlexible: 'NO',
    requestedEventTimes: '13:00 - 17:00',
    groupSize: 'V1 - 100\nV2 - 70',
    vessels: 'WEOTT II (Avontuur)',
    market: 'Corporate',
    yearOfEvent: 2026,
    assignedRep: 'Katherine',
    groupSizeQuote: 70,
    eventDateFlexibleBool: false,
    eventDateDisplay: 'Thursday 23rd July 2026',
    progressNotes:
      'DEMO gold scenario WE.18759 Summer V2 — 70 guests, substantial canapés. Use quote version V2.',
    quoteWeottCost: 8900.1,
    quoteMarginPercent: 25,
    quoteWeeklyPeriod: 'Mon to Thur',
    quoteDayPeriod: 'Daytime',
    quoteGroupBracket: 'Standard',
  },
  {
    id: 18937,
    referenceNumber: 'WE.18937',
    name: 'Loretta Greeley-Ward',
    companyName: 'Caribou Events',
    companySector: 'Events & Event Agencies',
    email: 'loretta@caribouevents.com',
    phone: '07749 469 247',
    jobRole: 'Founder',
    budget: 'TBC',
    repeatClient: 'No',
    preparedBy: 'Natasha',
    status: 'Agent - Did not chase',
    liveDead: 'LIVE',
    source: 'Event Agency',
    enquiryDate: '22-07-2026',
    eventType: 'Wedding Transfer',
    fullEventDate: 'Sunday 5th September 2027',
    eventDateFlexible: 'TBC',
    requestedEventTimes: '14:30 - 16:30',
    groupSize: 150,
    vessels: 'WEOTT II (Avontuur)',
    market: 'Wedding',
    yearOfEvent: 2027,
    assignedRep: 'Natasha',
    groupSizeQuote: 150,
    eventDateFlexibleBool: true,
    eventDateDisplay: 'Date TBC',
    progressNotes:
      'DEMO gold scenario WE.18937 Wedding Transfer V2 — agent, no commission.',
    quoteWeottCost: 10462.17,
    quoteMarginPercent: 20,
    quoteWeeklyPeriod: 'Mon to Thur',
    quoteDayPeriod: 'Daytime',
    quoteGroupBracket: 'Standard',
  },
  {
    id: 18931,
    referenceNumber: 'WE.18931',
    name: 'Mia Cruickshank',
    companyName: 'Databarracks',
    companySector: 'Technology & Software',
    email: 'Mia.cruickshank@databarracks.com',
    phone: '07596 863 974',
    jobRole: 'Events Manager',
    budget: '£9,000 to £9,999',
    repeatClient: 'No',
    preparedBy: '',
    status: 'First contact made',
    liveDead: 'LIVE',
    source: 'Chatbot Form',
    enquiryDate: '21-07-2026',
    eventType: 'Team Building',
    fullEventDate: 'Thursday 17th September 2026',
    eventDateFlexible: 'TBC',
    requestedEventTimes: 'V1 18:00 - 22:00 / V2 13:00 -17:00',
    groupSize: 80,
    vessels: 'WEOTT I (Rose)',
    market: 'Corporate',
    yearOfEvent: 2026,
    assignedRep: '',
    groupSizeQuote: 80,
    eventDateFlexibleBool: true,
    eventDateDisplay: 'Date TBC',
    progressNotes:
      'DEMO gold scenario WE.18931 Team Building V2 — Rose evening or Elizabethan daytime.',
    quoteWeottCost: 18982.51,
    quoteMarginPercent: 25,
    quoteWeeklyPeriod: 'Mon to Thur',
    quoteDayPeriod: 'Daytime',
    quoteGroupBracket: 'Standard',
  },
];
