// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pixel-clone-calendar/CalendarApp.tsx": () => import("../components/mockups/pixel-clone-calendar/CalendarApp.tsx"),
  "./components/mockups/pixel-clone-dashboard/WorkspaceDashboard.tsx": () => import("../components/mockups/pixel-clone-dashboard/WorkspaceDashboard.tsx")
};
